import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div style={{height:"50px", background:"red"}}>
        <div>
        <Link href="/blog/123">blog</Link>
        <Link href="/city/london">City</Link>
        <Link href="/dashboard/analytics">Analytics page</Link>
        <Link href="/dashboard/settings/passwords">Password</Link>
        <Link href="/dashboard/settings/profile">Profile</Link>
        <h1>all links added now</h1>
        </div>
        <Navbar/>
      </div>
        {children}
      </body>
    </html>
  );
}